spring:
  application:
    name: Order-Management
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ordersdb}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  api-docs:
    path: /api-docs
  security:
    user:
        name: user
        password: password
auth0:
  audience: ${AUTH0_AUDIENCE:localhostapi}
  domain: ${AUTH0_DOMAIN:dev-klozqcyixv5zgyqe.eu.auth0.com}
  clientId: ${AUTH0_CLIENT_ID:IpgwJDidQtNH29EsRQIX1E8iX7TgTuCo}
  clientSecret: ${AUTH0_CLIENT_SECRET:Z8yEyvjZ4wReSPE5-i_bbnL6m3rpmUypb_xKkAoXir3CMy7e2h8REwE58nWRONQ5}